table Gender
	lineageTag: 3bd88dc0-3365-46f4-a1c5-8246808b60ff

	column GenderID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c481cc28-77d3-49af-acf2-572bf4b2d3e4
		summarizeBy: none
		sourceColumn: GenderID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 8a1517e1-b947-48e3-86d7-00418f8c7158
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	partition Gender = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/jeanguerrapty/online_food_analysis/main/transformed_data/cleaned_onlinefoods.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"age", Int64.Type}, {"gender", type text}, {"marital_status", type text}, {"occupation", type text}, {"educational_qualifications", type text}, {"family_size", Int64.Type}, {"output", type text}, {"feedback", type text}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"age", "Age"}, {"gender", "Gender"}, {"marital_status", "Marital Status"}, {"occupation", "Occupation"}, {"educational_qualifications", "Studies"}, {"family_size", "Family Size"}, {"feedback", "Feedback"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"output"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Columns",{"Gender"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index1" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Index1",{{"Index", "GenderID"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns1",{"GenderID", "Gender"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

