table 'Marital Status'
	lineageTag: d3175d73-7bb2-4a45-bd14-37750f6a0918

	column MaritalStatusID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ff933ef4-753c-494f-adb7-7d4ea4e2ec11
		summarizeBy: none
		sourceColumn: MaritalStatusID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Marital Status'
		dataType: string
		lineageTag: f979101f-1494-42dd-8bd9-a749de0f24f4
		summarizeBy: none
		sourceColumn: Marital Status

		annotation SummarizationSetBy = Automatic

	partition 'Marital Status' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/jeanguerrapty/online_food_analysis/main/transformed_data/cleaned_onlinefoods.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"age", Int64.Type}, {"gender", type text}, {"marital_status", type text}, {"occupation", type text}, {"educational_qualifications", type text}, {"family_size", Int64.Type}, {"output", type text}, {"feedback", type text}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"age", "Age"}, {"gender", "Gender"}, {"marital_status", "Marital Status"}, {"occupation", "Occupation"}, {"educational_qualifications", "Studies"}, {"family_size", "Family Size"}, {"feedback", "Feedback"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"output"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Columns",{"Marital Status"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index1" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Index1",{{"Index", "MaritalStatusID"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns1",{"MaritalStatusID", "Marital Status"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

