table Occupation
	lineageTag: f0d54cba-5ffc-41d4-af95-fa1080a83cab

	column Occupation
		dataType: string
		lineageTag: 1df04769-3a6f-4677-b480-afe5ca968bbf
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column OccupationID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7792d5ad-fb60-4257-be4b-7e71c62660b2
		summarizeBy: none
		sourceColumn: OccupationID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Occupation = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/jeanguerrapty/online_food_analysis/main/transformed_data/cleaned_onlinefoods.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"age", Int64.Type}, {"gender", type text}, {"marital_status", type text}, {"occupation", type text}, {"educational_qualifications", type text}, {"family_size", Int64.Type}, {"output", type text}, {"feedback", type text}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"age", "Age"}, {"gender", "Gender"}, {"marital_status", "Marital Status"}, {"occupation", "Occupation"}, {"educational_qualifications", "Studies"}, {"family_size", "Family Size"}, {"feedback", "Feedback"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"output"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Columns",{"Occupation"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Duplicates","House wife","House Wife",Replacer.ReplaceText,{"Occupation"}),
				    #"Added Index1" = Table.AddIndexColumn(#"Replaced Value", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Index1",{{"Index", "OccupationID"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

