table Studies
	lineageTag: ab313aa4-2424-42e8-8e55-ea4bf574a575

	column StudiesID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: daa8c050-6a0e-4f38-9c24-09241f00ea24
		summarizeBy: none
		sourceColumn: StudiesID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Studies
		dataType: string
		lineageTag: 51d4a3c5-0636-4b44-af90-2b74faf806d9
		summarizeBy: none
		sourceColumn: Studies

		annotation SummarizationSetBy = Automatic

	partition Studies = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/jeanguerrapty/online_food_analysis/main/transformed_data/cleaned_onlinefoods.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"age", Int64.Type}, {"gender", type text}, {"marital_status", type text}, {"occupation", type text}, {"educational_qualifications", type text}, {"family_size", Int64.Type}, {"output", type text}, {"feedback", type text}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"age", "Age"}, {"gender", "Gender"}, {"marital_status", "Marital Status"}, {"occupation", "Occupation"}, {"educational_qualifications", "Studies"}, {"family_size", "Family Size"}, {"feedback", "Feedback"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"output"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns","House wife","House Wife",Replacer.ReplaceText,{"Occupation"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Replaced Value",{"Studies"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index1" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Index1",{{"Index", "StudiesID"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns1",{"StudiesID", "Studies"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

